
ALTER TABLE Beneficiarios
ADD CONSTRAINT FK_Beneficiarios_Clientes
FOREIGN KEY (IdCliente)
REFERENCES Clientes (Id);


CREATE UNIQUE INDEX UX_BENEFICIARIOS_IdCliente_CPF
    ON BENEFICIARIOS (IDCLIENTE, CPF);

