CREATE PROC FI_SP_InsBenef
    @NOME VARCHAR(50),
    @CPF  VARCHAR(11),
    @IDCLIENTE  BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE)
    VALUES (@NOME, @CPF, @IDCLIENTE);

    SELECT SCOPE_IDENTITY()
END
